[envs]
test = "devtools/conda-envs/test_env.yml"
user = "devtools/conda-envs/user_env.yml"
docs = "devtools/conda-envs/docs_env.yml"

[aliases]
greet = "echo hello world"

[aliases.docs]
cmd = "sphinx-build -j auto docs docs/_build/html"
chdir = true
env = "docs"
description = "Build the docs with Sphinx"

[aliases.test]
cmd = "pytest soap/tests"
chdir = true
env = "test"
description = "Run unit and regression tests with pytest"
passthrough_args = true
